apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-webapp-env
data:
  # CRITICAL PERFORMANCE FIX
  DEBUG: "False"  # This alone can reduce memory usage by 30-50%
  DJANGO_LOG_LEVEL: "WARNING"  # Reduce logging overhead
  ALLOWED_HOSTS: "*"
  BACKEND_ADDRESS: "https://demo-webapp.krfa-lab.com"
  BACKEND_SAME_HOST: "False" #Needs to be set to False if it's deployed on Kubernetes and behind an Ingress
  TIME_ZONE: "Europe/Zurich"
  CORS_ALLOW_ALL_ORIGINS: "True"
  CSRF_TRUSTED_ORIGINS: "https://*.krfa-lab.com"
  DB_USER: "postgres"
  DB_NAME: "demowebapp"
  DB_HOST: "psql-italynorth-pgsql-01.postgres.database.azure.com"
  DB_PORT: "5432"
  # Optimized Azure Monitor settings
  ENABLE_AZURE_MONITOR: "True"
  AZURE_MONITOR_SAMPLING_RATE: "1.0"  # 100% sampling for demo
  AZURE_MONITOR_ENABLE_METRICS: "true"
  AZURE_MONITOR_METRICS_INTERVAL: "600000"  # 10 minutes
  AZURE_MONITOR_INSTRUMENT_DB: "true"  # Enable for testing
  AZURE_MONITOR_INSTRUMENT_HTTP: "true"  # Enable for testing
  AZURE_MONITOR_MAX_QUEUE_SIZE: "256"  # Reduced from 512
  AZURE_MONITOR_MAX_EXPORT_BATCH_SIZE: "64"  # Reduced from 128
  AZURE_MONITOR_EXPORT_TIMEOUT: "5000"   # 5 seconds for testing
  AZURE_MONITOR_SCHEDULE_DELAY: "2000"   # 2 seconds for testing
  # Gunicorn performance settings
  GUNICORN_WORKERS: "2"  # Reduced from 4
  GUNICORN_MAX_REQUESTS: "1000"  # Prevent memory leaks
  GUNICORN_MAX_REQUESTS_JITTER: "100"
  GUNICORN_TIMEOUT: "30"
  GUNICORN_KEEPALIVE: "2"
  # Database optimization
  DB_CONN_MAX_AGE: "300"  # 5 minutes connection reuse
  DB_OPTIONS_STATEMENT_TIMEOUT: "15000"  # 15 seconds
  DB_OPTIONS_CONNECT_TIMEOUT: "15"
  # Session optimization
  SESSION_COOKIE_AGE: "1800"  # 30 minutes
  SESSION_ENGINE: "django.contrib.sessions.backends.cached_db"
  SESSION_SAVE_EVERY_REQUEST: "False"
  AZURE_FOUNDRY_ENDPOINT: "https://aif-francecentral-demowebapp-ai-01.services.ai.azure.com/api/projects/demo-webapp"
