apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-webapp
  template:
    metadata:
      labels:
        app: demo-webapp
    spec:
      containers:
        - name: demo-webapp
          image: acritalynorth01.azurecr.io/demo-webapp:latest # Replace with your image
          ports:
            - containerPort: 8000
          # Optimized resource limits and requests
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "400Mi"
              cpu: "400m"
          # Improved health checks
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Startup probe to prevent premature kills
          startupProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 20
          env:
            # Performance environment variables
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONHASHSEED
              value: "random"
            # Existing secret environment variables
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: application-connection-string
                  key: secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: secret
            - name: AZURE_FOUNDRY_AGENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-ai-foundry-agent-id
                  key: secret
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-client-id
                  key: secret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-tenant-id
                  key: secret
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-client-secret
                  key: secret
          envFrom:
            - configMapRef:
                name: demo-webapp-env
          volumeMounts:
          - name: kv-italynorth-aks-01
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: kv-italynorth-aks-01
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "kv-italynorth-aks-01"