apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-webapp

commonLabels:
  app: demo-webapp

resources:
  - namespace.yaml
  - secretproviderclass.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml

images:
  - name: acritalynorth01.azurecr.io/demo-webapp
<<<<<<< HEAD
    newTag: develop-9f1f0d232cef08ef9f6d4910b43ae014bfeda55f
=======
    newTag: develop-b287f5f813bcc50da28db9c181928cba9bc7bfea
>>>>>>> af07196 (Fix : test issue)
