apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-webapp

commonLabels:
  app: demo-webapp

resources:
  - namespace.yaml
  - secretproviderclass.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml

images:
  - name: acritalynorth01.azurecr.io/demo-webapp
    newTag: d136c9b57cdbe60554cc56435910690e080c4173