apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-webapp

commonLabels:
  app: demo-webapp

resources:
  - namespace.yaml
  - secretproviderclass.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml

# No images section here - overlays will handle image tags
