apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-webapp-env
  namespace: demo-webapp
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  BACKEND_ADDRESS: "https://demo-webapp.krfa-lab.com"
  BACKEND_SAME_HOST: "False" #Needs to be set to False if it's deployed on Kubernetes and behind an Ingress
  TIME_ZONE: "CET"
  CORS_ALLOW_ALL_ORIGINS: "True"
  CSRF_TRUSTED_ORIGINS: "https://*.krfa-lab.com"
  DB_USER: "postgre"
  DB_NAME: "demowebapp"
  DB_HOST: "demo-webapp-aks-01.postgres.database.azure.com"
  DB_PORT: "5432"
  ENABLE_AZURE_MONITOR: "True"
  ENABLE_LIVE_METRICS: "True"
