apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-italynorth-aks-01
spec:
  provider: azure
  secretObjects:
    - secretName: application-connection-string
      type: Opaque
      data:
        - objectName: applicationConnectionString
          key: secret
    - secretName: secret-key
      type: Opaque
      data:
        - objectName: secretKey
          key: secret
    - secretName: db-password
      type: Opaque
      data:
        - objectName: dbPassword
          key: secret
    - secretName: azure-ai-foundry-key
      type: Opaque
      data:
        - objectName: azureAiFoundryKey
          key: secret
    - secretName: azure-ai-foundry-agent-id
      type: Opaque
      data:
        - objectName: azureAiFoundryAgentId
          key: secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 824ae564-a13f-4c1b-9f89-14f12735260b
    keyvaultName: kv-italynorth-aks-01
    objects: |
      array:
        - |
          objectName: applicationConnectionString
          objectType: secret
        - |
          objectName: secretKey
          objectType: secret
        - |
          objectName: dbPassword
          objectType: secret
        - |
          objectName: azureAiFoundryQuey
          objectType: secret
        - |
          objectName: azureAiFoundryAgentId
          objectType: secret
    tenantId: af2dd59c-81cf-4524-8d9e-6d8254d02438