# Generated by Django 5.2.5 on 2025-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='azure_run_id',
            field=models.CharField(blank=True, help_text='Azure AI run ID for tracking', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', help_text='Status of message processing for Azure AI responses', max_length=20),
        ),
    ]
